language: swift
os: osx
osx_image: xcode10.3
xcode_project: GitEncryptionTest.xcodeproj
xcode_scheme: GitEncryptionTest-Package
xcode_destination: platform=macOS
before_install:
- openssl enc -aes-256-cbc -d -in Sources/GitEncryptionTest/awsKeypair.pem.enc -out Sources/GitEncryptionTest/awsKeypair.pem -k $AES_PASS
- openssl enc -aes-256-cbc -d -in Sources/GitEncryptionTest/Config.json.enc -out Sources/GitEncryptionTest/Config.json -k $AES_PASS
- openssl enc -aes-256-cbc -d -in Sources/GitEncryptionTest/OtherConfig.json.enc -out Sources/GitEncryptionTest/OtherConfig.json -k $AES_PASS
- swift package generate-xcodeproj
deploy:
  provider: script
  script: bash .docker_push $AES_PASS
  on:
    branch: master
