language: swift
os: osx
osx_image: xcode10.3
before_script:
- swift package generate-xcodeproj
xcode_project: GitEncryptionTest.xcodeproj
xcode_scheme: GitEncryptionTest-Package
xcode_destination: platform=macOS
before_install:
- openssl aes-256-cbc -K $encrypted_74a221dce6ae_key -iv $encrypted_74a221dce6ae_iv
  -in Config.json.enc -out Config.json -d
