language: swift
os: osx
osx_image: xcode10.3
xcode_project: GitEncryptionTest.xcodeproj
xcode_scheme: GitEncryptionTest-Package
xcode_destination: platform=macOS
before_install:
- openssl enc -aes-256-cbc -d -in awsKeypair.pem.enc -out awsKeypair.pem -k $AES_PASS
- openssl enc -aes-256-cbc -d -in Config.json.enc -out Config.json -k $AES_PASS
- openssl enc -aes-256-cbc -d -in OtherConfig.json.enc -out OtherConfig.json -k $AES_PASS
- swift package generate-xcodeproj
deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master
