language: swift
os: osx
osx_image: xcode10.3
xcode_project: GitEncryptionTest.xcodeproj
xcode_scheme: GitEncryptionTest-Package
xcode_destination: platform=macOS
before_install:
- openssl aes-256-cbc -K $encrypted_74a221dce6ae_key -iv $encrypted_74a221dce6ae_iv
  -in Sources/GitEncryptionTest/configs.tar.enc -out Sources/GitEncryptionTest/configs.tar -d
- tar xvf Sources/GitEncryptionTest/configs.tar -C Sources/GitEncryptionTest
- swift package generate-xcodeproj
