language: swift
os: osx
osx_image: xcode10.3
xcode_project: GitEncryptionTest.xcodeproj
xcode_scheme: GitEncryptionTest-Package
xcode_destination: platform=macOS
before_install:
- openssl aes-256-cbc -K $encrypted_74a221dce6ae_key -iv $encrypted_74a221dce6ae_iv
  -in Sources/GitEncryptionTestOther/Config.json.enc -out Sources/GitEncryptionTest/OtherConfig.json -d
- openssl aes-256-cbc -K $encrypted_74a221dce6ae_key -iv $encrypted_74a221dce6ae_iv
  -in Sources/GitEncryptionTest/Config.json.enc -out Sources/GitEncryptionTest/Config.json -d
- swift package generate-xcodeproj
